config/routes.rb
Rails.application.routes.draw do

  match 'users/change_password', to: "users#change_password", via: [:get,:post]
  match 'users/roles', to: 'users#roles', via: [:get,:post]
  resource :users, only: [:create, :reset_password, :set_role, :set_status], via: [:post,:get]
  get 'session', to: 'sessions#destroy'
  resource :session
  match ':controller(/:action(/:id))', via: [:get, :post], controller: /[^\/]+_configurations/, id: /[^\/]+/
  match ':controller(/:action(/:id))', via: [:get, :post]

  root 'patients#index'
end

app/models/exam.rb
=begin rdoc
=Description
The Exam model is an active record representation
of the exams table in the database.

It uses active record to define association methods between
itself and the reports, jobs, and patients models. It defines
convenience methods for getting the most recent values of the
jobs and reports associations.

==Named Scopes
*by_exam_description*(_description_) - takes and exam description
and queries the exams table filtering by that field.  This uses
the Search module to generate permutations of the exam description

=end
class Exam < ActiveRecord::Base
  self.primary_key = "exam_id"
  belongs_to :patient
  has_many :reports
  has_many :jobs

  def self.filter_cancelled(exams)
    exams.to_ary.delete_if {|e| e.last_report and e.last_report.status == "CANCELED" }
  end

  scope :by_exam_description, lambda {|ed|
    query = Search::Query.new(ed)
    conds = query.conditions(:exam_description => lambda { query.term_to_name_string(:exam_description) })
    where(*conds)
  }

  def latest_information
    @latest_information ||= ViewExamStatus.where("exam_id = ?",self.id).take
  end

  # Gets the most recent report associated with this exam
  def last_report
    if self.latest_information and self.latest_information.report_id
      @last_report ||= Report.find(self.latest_information.report_id)
    else
      nil
    end
  end

  # Gets the most recent job associated with this exam
  def job
    @job ||= Job.where("exam_id = ?", self.id).order("modified_date DESC").first
  end

  def job_transaction
    @job_transaction ||= JobTransaction.where("job_id = ?", self.job.id).order("modified_date DESC").first if self.job
  end
end

app/models/patient.rb
=begin rdoc
=Description
The Patient model is an active record representation
of the patients table in the database.

It uses active record to define association methods between
itself and the Report, Exam, and RsnaId models.
=end
class Patient < ActiveRecord::Base
  self.primary_key = "patient_id"
  has_many :reports, :through => :exams
  has_many :exams
  has_many :job_sets

  # This builds a search query using the Search model and a with_scope that joins the RsnaId model
  # terms_for_search can be a string or a hash of field value pairs, e.g:
  #
  #   Patient.search("John Doe")
  #   Patient.search(:mrn => "0982734", :rsna_id => "9823", :patient_name => "Doe, John")
  def self.search(*terms_for_search)
    self.unscoped.where(Search::Query.new(*terms_for_search).conditions)
  end

  # Accessor for getting the exact value of patient_name in the database.  This usually contains
  # an HL7 version of the name, i.e., Doe^John^^ hence the name of the method.
  def hl7_patient_name
    self.attributes['patient_name']
  end

  # This takes the raw value of the patient name in the database and formats it with commas instead of carrots
  def patient_name
    self.attributes['patient_name'].split("^").join(", ")
  end

  def rsna_id_email
    @rsna_id_email_record = JobSet.where("patient_id = ? AND email_address IS NOT NULL",self.id).order("job_set_id desc").first
    @rsna_id_email_record.email_address if @rsna_id_email_record
  end

  def phone_number
    @phone_number_record = JobSet.where("patient_id = ? AND phone_number IS NOT NULL",self.id).order("job_set_id desc").first
    @phone_number_record.phone_number if @phone_number_record
  end

  def consented?
    if self.consent_timestamp and ((Time.now - self.consent_timestamp) / 86400) <= EdgeConfiguration.consent_duration
      true
    else
      false
    end
  end

  protected
  # Pads the patient id supplied by the hl7 with the required number of zeros so that the RsnaId
  # matches the formatting spec supplied
  def padded_patient_id
    if 5 - self.id.to_s.size > 0
      "0"*(5-self.id.to_s.size) + self.id.to_s
    else
      self.id
    end
  end

end

app/controllers/exams_controller.rb
=begin rdoc
=Description
Handling of adding and deleting exams from the cart and the creation of jobs when sending the cart.
=end
class ExamsController < ApplicationController
  before_filter :authenticate
  before_filter :get_cart
  before_filter :force_patient, :except => [:retry_job]
  hipaa_filter

  # List the exams for the specified patient
  def index
    @exams = Exam.filter_cancelled(@patient.exams)
    @autoprint_rsna_id = (["send_to_site", "rsna_id", "standard"].include?(params[:logic_type]) ? true : false)
    @send_components = {:email_address => params[:email_address], :token => params[:token], :formatted_dob => params[:formatted_dob], :access_code => params[:access_code], :logic_type => params[:logic_type]}
  end

  def print_patient_info
    @token = params[:token]
    @email_address = params[:email_address]
    @logic_type = params[:logic_type]
    if @logic_type != "send_to_site"
      render :layout => "layouts/print", :template => "exams/print_patient_info"
    else
      render :layout => "layouts/print", :template => "exams/print_site_to_site_info"
    end
  end

  # Filter the patients exams by the exam description
  def filter
    @exams = @patient.exams
    @exams = @exams.by_exam_description(params[:filter]) unless params[:filter].blank?
    Exam.filter_cancelled(@exams) unless params[:show_cancelled].blank?
    render :partial => "exams/results", :locals => {:exams => @exams, :patient => @patient}
  end

  # Given the cart, create the job set, jobs and transaction entries
  def send_cart
    case params[:override_delay]
    when '1'
      delay_in_hrs = 0
    when '2'
      delay_in_hrs = 0
      send_on_complete = true
    else
      delay_in_hrs = JobSet.delay_in_hrs;
    end
    send_on_complete ||= false

    if params[:autosend] and !@patient.autosend
      @patient.autosend = true
      @patient.save
    elsif params[:autosend].nil? and @patient.autosend
      @patient.autosend = false
      @patient.save
    end

    @job_set = JobSet.new({
                            :patient_id => @patient.id,
                            :user_id => @user.id,
                            :email_address => params[:email],
                            :phone_number => params[:phone],
                            :modified_date => Time.now,
                            :delay_in_hrs => delay_in_hrs,
                            :send_on_complete => send_on_complete,
                            :use_rsna_id => (params[:new_email] == "true" ? false : true),
                            :send_to_site => (not params[:send_to_site].blank?)
                          })
    if @job_set.save
      @cart.each do |exam_id|
        time = Time.now
        job = Job.create(:exam_id => exam_id, :job_set_id => @job_set.id, :modified_date => time)
        JobTransaction.create(:job_id => job.id, :status_code => 1, :comments => "Queued", :modified_date => time)
      end
      cart_op {|cart| [] }
      flash[:notice] = "Exams queued and patient information printed"
      render :partial => "exams/token_info"
    else
      render :text => "An error occured while saving your cart information"
    end
  end

  # Show the cart
  def show_cart
    @exams = @cart.collect {|id| Exam.find(id) }
    @patient = @exams.first.patient if @exams and @exams.size > 0
  end

  # Add an exam to the cart
  def add_to_cart
    cart_op do |cart|
      if params[:id].class == Array
        params[:id].collect!(&:to_i)
        params[:id].delete_if {|id| cart.include?(id) }
        cart = cart + params[:id]
      else
        cart << params[:id].to_i if not params[:id].blank? and not get_cart.find {|i| i == params[:id].to_i }
      end
      cart
    end
    render_cart_size
  end

  # Remove an exam from the cart
  def delete_from_cart
    cart_op {|cart| cart.delete(params[:id].to_i); cart }
    render_cart_size
  end

  # Empty the cart
  def empty_cart
    cart_op {|cart| [] }
    flash[:notice] = "Emptied Shopping Cart"
    redirect_to :action => :index
  end

  # Create new transaction to retry failed job
  def retry_job
    JobTransaction.create(:job_id => params[:id], :status_code => 1, :comments => "Retry", :modified_date => Time.now)
  end

end

app/views/exams/_results.html.erb
<%= rsna_table_for exams, sortable: true, id: "exams_for_patient", class: "table table-bordered table-striped" do |st| %>
  <% st.column("") {|e| cart_add_button(@cart,e) } %>
  <% st.column("Accession #") {|e| h e.accession_number } %>
  <% st.column("Exam Desc") {|e| h e.exam_description } %>
  <% st.column("Most Recent Change") {|e| h e.latest_information.status_timestamp.to_s(:rfc822) if e.latest_information } %>
  <% st.column("Status") {|e| h status_for(e) } %>
  <%# st.column("Send Status") {|e| h send_status_for(e) } %>
<% end %>

app/views/exams/_token_dialog.html.erb
<div id="cart-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" role="button">&times;</button>
        <h4 class="modal-title">Send Cart</h4>
      </div>
      <div class="modal-body" id="cart-dialog">

	  <div id="errorExplanation" style="display: none;">
	    <h2>Errors occured while trying to send the cart</h2>
	    <p>There was a problem with the following fields</p>
	    <ul>
	    </ul>
	  </div>
	  <%= form_tag({action: "send_cart", controller: "exams"}, {id: 'cart-form', role: "form", style: "display: inline;"}) do %>
	  <% exams.each do |exam| %>
	    <%= hidden_field_tag "exam_ids[]", exam.id %>
	  <% end %>

	  <div id="cart-send-type-dialog">
	    <div class="row">
	      <div class="col-xs-6 center">
		Send the exams so that the patient can collect them from a PHR.
	      </div>
	      <div class="col-xs-6 center">
		Send the exams so that the another site can collect them.
	      </div>
	    </div>

	    <div class="row">
	      <div class="col-xs-6 center">
		<input type="button" value="Send to Patient" class="send-type-choice btn btn-primary" />
	      </div>
	      <div class="col-xs-6 center">
		<input type="button" value="Send to Site" class="send-type-choice btn btn-primary" data="site-to-site" />
	      </div>
	    </div>
	    <div class="row">
	      <div class="col-xs-6 center">
		<div class="checkbox">
		  <label>
		    <%= check_box_tag 'autosend', '1', @patient.autosend %>
		    Send new exams automatically.
		  </label>
		</div>
	      </div>
	    </div>
	    <input type="hidden" value="" name="send_type" />
	  </div>

	  <!-- Previously sent scenario -->
	  <div id="cart-use-previous-dialog" style="display: none;">
	    <p>This patient already has an account. Would you like to use the patient's previous access code, email address (<%= @patient.rsna_id_email %>) and phone number (<%= @patient.phone_number %>)?</p>
	    <input type="button" value="Yes" class="use-old-button btn btn-primary" />
	    <input type="button" value="No" class="use-old-button btn btn-default" />
	  </div>

	  <!-- Send urgency dialog -->
	  <div id="cart-send-dialog" style="display: none;">
	    <div class="container-fluid">
	      <div class="row">

		<div class="col-xs-4 center">
		  Delay to allow care provider to communicate with patient.
		</div>

		<div class="col-xs-4 center">
		  Send as soon as final report available.
		</div>

		<div class="col-xs-4 center">
		  Send now, even if no final report available.
		</div>

	      </div>

	      <div class="row">
		<div class="col-xs-4 center">
		  <%= link_to("Routine", "#", class: "send-cart-button btn btn-primary", data: 0) %>
		</div>

		<div class="col-xs-4 center">
		  <%= link_to("When final report available", "#", class: "send-cart-button btn btn-primary", data: 1) %>
		</div>

		<div class="col-xs-4 center">
		  <%= link_to("Immediately", "#", class: "send-cart-button btn btn-primary", data: 2) %>
		</div>
	      </div>
	    </div>

	    <input type="hidden" name="override_delay" value="0" />
	  </div>

	  <!-- Enter email address dialog -->
	  <div id="cart-email-dialog" style="display: none;">
	    <div class="form-group">
              <label>Patient Email</label>
              <input class="form-control" name="email" type="text" value="<%= @exams.first.patient.rsna_id_email || @patient.email_address %>" />
	    </div>
	    <div class="form-group">
              <label>Patient Mobile Phone Number</label>
              <input class="form-control" name="phone" type="text" value="<%= @patient.phone_number %>" />
	    </div>

	    <%= submit_tag("Next", id: "validate-email-button", class: "btn btn-primary") %>
	  </div>

	  <!-- submission spinner -->
	  <div id="submit_spinner" class="progress progress-striped active margin-top" style="display: none; width: 100%;">
	    <div class="progress-bar" style="width: 100%"></div>
	  </div>

	  <% end %>
	</div>
      </div>
    </div>
  </div>
</div>

app/views/exams/_token_info.html.erb
<h1>Cart Queued for Sending</h1>

<div class="demographic">
  <label>Patient Name:</label>
  <span><%= @patient.patient_name %></span>
</div>

<div class="demographic">
  <label>Access Code:</label>
  <span><%= format_token(@job_set.send_components[:access_code]) %></span>
</div>

<div class="demographic">
  <label>Date of Birth:</label>
  <span><%= @patient.dob %></span>
</div>

<% if @job_set.logic_type == :site_to_site %>
<div>
  Send printout to a destination site in the Image Share Network to enable them to retrieve exam.
</div>
<% end %>
<%= link_to("Print", {:controller => :exams, :action => :index, logic_type: @job_set.logic_type, :patient_id => @patient.id}.merge(@job_set.send_components), class: "btn btn-primary") %>

app/views/exams/index.html.erb
<%= content_for(:title, "Exams for #{@patient.patient_name}") %>

<%= link_to("Reprint Token", "#", class: "btn btn-primary", onclick: "window.open('#{url_for({:controller => :exams, :action => :print_patient_info}.merge(@send_components))};return false;") if @autoprint_rsna_id %>

<%= form_for :search, :html => {id: "filter_form", method: 'get', class: "form-inline", onsubmit: "search_or_filter('/exams/filter',$('#filter_form').serialize()); return false;"} do |f| %>
  <div class="form-group">
    <label for="filter">Exam description</label>
    <input name="filter" class="form-control" type="text" />
  </div>
  <div class="form-group">
    <label for="show_cancelled"><input type="checkbox" name="show_cancelled" /> Show Cancelled Exams?</label>
  </div>

  <%= submit_tag "Filter", class: "btn btn-primary" %>

<% end %>

<div id="search_spinner" class="progress progress-striped active margin-top" style="display: none; width: 560px;">
  <div class="progress-bar" style="width: 100%"></div>
</div>

<%= button_to("Select All","#", id: "select-all-button", class: "btn btn-primary") %>

<%= content_tag :div, id: "search_results", class: "margin-top" do %>
  <%= render partial: "exams/results", locals: {exams: @exams, patient: @patient} %>
<% end %>

<%= javascript_tag("window.open('#{url_for({controller: :exams, action: :print_patient_info}.merge(@send_components))}');") if @autoprint_rsna_id %>

app/views/exams/print_patient_info.es.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">

<%= image_tag("IMageShareLogo.png") %>
<div class="pull-right"><%= image_tag("nibib-logo.png") %></div>
<div class="subtitle">RSNA Image Share le ofrece control sobre sus imágenes médicas</div>

<p>
Gracias por considerar la red de Image Share la cual le permite controlar los resultados de sus estudios de imágenes médicas.  La misma fue desarrollada por la Sociedad Radiológica de América del Norte (RSNA por sus siglas en inglés) y sus socios con fondos del Instituto Nacional de Imagenología Biomédica y de Bioingeniería.
</p>

<p>
Dos pasos sencillos para usar Image Share:
</p>

<ol>
  <li>
    <p>
      Staff will send your imaging records to a secure online data repository called the Image Clearinghouse so you can access them.
      <strong>Note that the records may not be available in the Clearinghouse for up to 3 days to allow your care team to communicate with you about the results.</strong>
      <% if EmailConfiguration.value_for("patient_email") == "true" %>
	  You will receive an email notification when your information is ready to be accessed.
      <% end %>
    </p>
  </li>

  <li>
    <p>
      Cree su cuenta en el sistema de expediente personal de imágenes médicas
    </p>

    <ul>
      <li><strong>DICOM Grid:</strong> <a class="highlight" href="http://imageshare.dicomgrid.com">http://imageshare.dicomgrid.com</a></li>
      <li><strong>itMD:</strong> <a class="highlight" href="http://share.itMD.net/claim">http://share.itMD.net/claim</a></li>
      <li><strong>lifeIMAGE:</strong> <a class="highlight" href="https://cloud.lifeimage.com/rsna/phr">https://cloud.lifeimage.com/rsna/phr</a></li>
    </ul>

    <p class="margin-top">
      Each of these sites provides simple instructions to creating an account and use it to get your imaging results. Be sure to record your PHR account information and keep it secure, as you do with all your valuable online information.
    </p>
  </li>

  <li>
    <p>Para acceder a su cuenta y controlar sus resultados de estudios de imágenes, necesitará los siguientes datos:</p>

    <ul>
      <li>Fecha de nacimiento</li>
      <li>Código de Acceso:<strong> <%= format_token(params[:access_code]) %></strong></li>
    </ul>

    <p class="margin-top">
      Entre la información y accederá imágenes y reportes.  Usted puede usar su cuenta para compartir información con personas en quien confíe, incluyendo proveedores médicos.  Usted puede proveerle acceso para que vean sus imágenes y reportes mediante la internet..
    </p>

  </li>
</ol>

<p>
  More information about the Image Share network is available at <a class="highlight" href="http://www.rsna.org/Image_Share.aspx">http://www.rsna.org/Image_Share.aspx</a>.
</p>

<p class="description">
  <%= EdgeConfiguration.help_desk_message.html_safe %>
</p>

    </div>
  </div>
</div>

app/views/exams/print_patient_info.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">

<%= image_tag("IMageShareLogo.png") %>
<div class="pull-right"><%= image_tag("nibib-logo.png") %></div>
<div class="subtitle">Image Share Gives You Control of Your Medical Images</div>

<p>
Thanks for agreeing to try Image Share, a network that lets you take control of your medical imaging results. Image Share was developed by the Radiological Society of North America (RSNA) and its partners with funding from the National Institute of Biomedical Imaging and Bioengineering.
</p>

<p>
There are three simple steps to using Image Share:
</p>

<ol>
  <li>
    <p>
      Staff will send your imaging records to a secure online data repository called the Image Clearinghouse so you can access them.
      <strong>Note that the records may not be available in the Clearinghouse for up to 3 days to allow your care team to communicate with you about the results.</strong>
      <% if EmailConfiguration.value_for("patient_email") == "true" %>
	  You will receive an email notification when your information is ready to be accessed.
      <% end %>
    </p>
  </li>

  <li>
    <p>
      You need to create an account on one of the participating image-enabled personal health record(PHR) systems:
    </p>

    <ul>
      <li><strong>DICOM Grid:</strong> <a class="highlight" href="http://imageshare.dicomgrid.com">http://imageshare.dicomgrid.com</a></li>
      <li><strong>itMD:</strong> <a class="highlight" href="http://share.itMD.net/claim">http://share.itMD.net/claim</a></li>
      <li><strong>lifeIMAGE:</strong> <a class="highlight" href="https://cloud.lifeimage.com/rsna/phr">https://cloud.lifeimage.com/rsna/phr</a></li>
    </ul>

    <p class="margin-top">
      Each of these sites provides simple instructions to creating an account and use it to get your imaging results. Be sure to record your PHR account information and keep it secure, as you do with all your valuable online information.
    </p>
  </li>

  <li>
    <p>You use your PHR account to access and take control of your imaging results. You will need two pieces of information to access your information:</p>

    <ul>
      <li>Date of Birth</li>
      <li>Access Code:<strong> <%= format_token(params[:access_code]) %></strong></li>
    </ul>

    <p class="margin-top">
      Enter the information and retrieve the images and reports. You can then use your PHR account to share information with others you trust, including care providers. With your permission they can view the images and the report anywhere Internet access is available.
    </p>

  </li>
</ol>

<p>
  More information about the Image Share network is available at <a class="highlight" href="http://www.rsna.org/Image_Share.aspx">http://www.rsna.org/Image_Share.aspx</a>.
</p>

<p class="description">
  <%= EdgeConfiguration.help_desk_message.html_safe %>
</p>

    </div>
  </div>
</div>

app/views/exams/print_site_to_site_info.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">

<%= image_tag("IMageShareLogo.png") %>
<div class="pull-right"><%= image_tag("nibib-logo.png") %></div>
<div class="subtitle">Take Control of Your Medical Images</div>

<p>
  Staff at <%= EdgeConfiguration.site_id %> have made imaging records of the patient listed below available for you
  to access in delivering care to this patient. Your radiology department can retrieve these records for
  viewing and import using the RSNA Image Share Edge Server and the following information:

    <ul>
      <li>Patient Name: <%= @patient.patient_name %></li>
      <li>Date of Birth: <%= @patient.dob %></li>
      <li>Access Code:<strong> <%= format_token(params[:access_code]) %></strong></li>
    </ul>

</p>

<p>
  This message and the image records it references may be privileged, confidential, contain protected
  health information about an identified patient or be otherwise protected from disclosure. This
  information is intended to be communicated only to authorized care providers throught secure means
  adhering to relevant policies of both the sending and the recipient care sites. State and federal law
  protect the confidentiality of this information. If you are not the intended recipient of this message,
  you are prohibited from using, disclosing, reproducing or distributing this information; you should
  immediately notify the sender by telephone or e-mail and delete this message.
</p>

<p>
  If you have questions, have received this information inadvertently or encounter any problems accessing
  information, please contact the Image Sharing Help Desk:
</p>

<p>
  Email: helpdesk@imsharing.org
</p>

<p>
  Tollfree number: 1-855-IMSHARING (467-4274)
</p>

<p>
  Hours: 8am-8pm Eastern Time, Monday through Friday (except holidays)
</p>

    </div>
  </div>
</div>

app/views/exams/search.html.erb
<h1>Documents#search</h1>
<p>Find me in app/views/documents/search.html.erb</p>

app/views/exams/show_cart.html.erb
<% content_for(:title, "Shopping Cart") %>
<% content_for(:javascript_includes, javascript_include_tag("pages/cart.js")) %>

<% if @exams.size > 0 %>
  <%= rsna_table_for @exams, class: "table table-bordered table-striped" do |st| %>
    <% st.column("Accession #") {|e| h e.accession_number } %>
    <% st.column("Exam Desc") {|e| h e.exam_description } %>
    <% st.column("Exam Date") {|e| h e.modified_date.to_s(:rfc822) } %>
    <% st.column("") {|e| button_to("Remove From Cart", "#", id: "delete_link_#{e.id}", class: "btn btn-primary", onclick: "delete_from_cart('delete_link_#{e.id}', '#{e.id}');return false;") } %>
  <% end %>

<div>
  <%= link_to("Empty Cart", {action: "empty_cart", controller: "exams"}, class: "btn btn-primary") %>
  <%= link_to("Send Cart", "#", id: "send-cart-button", class: "btn btn-primary") %>
</div>

<%= render partial: "exams/token_dialog", locals: {exams: @exams} %>

<% else %>
 <div>Your shopping cart is empty</div>
<% end %>